apiVersion: v1
kind: Pod
metadata:
  name: http-pod
  labels:
    app: nginx #using the same label here to test out load balancing
spec:
  containers:
  - name: httpd
    image: httpd
    ports:
    - containerPort: 80
    - containerPort: 443
